# config/restrictions.yaml
restrictions:
  - type: "polygon"
    points:
      - {x: 1.0, y: 1.0}
      - {x: 2.0, y: 1.0}
      - {x: 2.0, y: 2.0}
      - {x: 1.0, y: 2.0}
  - type: "circle"
    points:
      - {x: 4.0, y: 4.0}
    radius: 1.5